#!/usr/bin/env python3
"""graphify: crawl the repo and write a compact code map to memory/system-reference.md.

Stdlib-only by design (tool priority: CLI > API > MCP; zero deps, zero infra).
- Python files under backend/ are parsed with `ast` (classes, functions, docstrings, imports).
- TS/TSX files under frontend/src/ and e2e/ are regex-parsed (exports, relative imports).

Usage:
  python3 scripts/graphify.py            # regenerate the map
  python3 scripts/graphify.py --check    # exit 1 if the map looks stale
"""
from __future__ import annotations

import ast
import re
import sys
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "memory" / "system-reference.md"
PY_ROOTS = ["backend"]
TS_ROOTS = ["frontend/src", "e2e"]
SKIP_DIRS = {"node_modules", ".venv", "__pycache__", ".git", "dist", "build", ".pytest_cache", "test-results", "playwright-report"}
MAX_DOC = 90  # chars of docstring kept per symbol


def iter_files(roots: list[str], exts: tuple[str, ...]):
    for root in roots:
        base = ROOT / root
        if not base.exists():
            continue
        for p in sorted(base.rglob("*")):
            if p.suffix in exts and p.is_file() and not (SKIP_DIRS & set(p.parts)):
                yield p


def doc1(node) -> str:
    d = ast.get_docstring(node) or ""
    return d.strip().splitlines()[0][:MAX_DOC] if d.strip() else ""


def parse_py(path: Path):
    try:
        tree = ast.parse(path.read_text(encoding="utf-8", errors="replace"))
    except SyntaxError as e:
        return {"error": f"syntax error: {e}"}
    mod = {"doc": doc1(tree), "classes": [], "functions": [], "imports": []}
    for node in tree.body:
        if isinstance(node, ast.ClassDef):
            methods = [n.name for n in node.body if isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef)) and not n.name.startswith("_")]
            mod["classes"].append((node.name, doc1(node), methods))
        elif isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            if not node.name.startswith("_"):
                args = [a.arg for a in node.args.args if a.arg not in ("self", "cls")]
                mod["functions"].append((node.name, ", ".join(args), doc1(node)))
        elif isinstance(node, (ast.Import, ast.ImportFrom)):
            names = [a.name for a in node.names] if isinstance(node, ast.Import) else [node.module or "."]
            mod["imports"] += [n for n in names if n and n.split(".")[0] in ("app", "tests")]
    return mod


TS_EXPORT = re.compile(r"^export\s+(?:default\s+)?(?:async\s+)?(function|const|class|interface|type|enum)\s+([A-Za-z0-9_]+)", re.M)
TS_IMPORT = re.compile(r"""^import\s+.*?from\s+['"](\.[^'"]+)['"]""", re.M)


def parse_ts(path: Path):
    text = path.read_text(encoding="utf-8", errors="replace")
    exports = [f"{name} ({kind})" for kind, name in TS_EXPORT.findall(text)]
    imports = TS_IMPORT.findall(text)
    return {"exports": exports, "imports": imports}


def rel(p: Path) -> str:
    return str(p.relative_to(ROOT))


def build() -> str:
    lines = [
        "# System reference (generated — do not edit)",
        "",
        f"Generated by `scripts/graphify.py` on {date.today().isoformat()}. Refresh: `python3 scripts/graphify.py`.",
        "",
    ]
    edges: list[tuple[str, str]] = []
    n_funcs = n_classes = n_exports = n_files = 0

    lines.append("## Backend (Python)")
    for f in iter_files(PY_ROOTS, (".py",)):
        info = parse_py(f)
        n_files += 1
        if "error" in info:
            lines.append(f"\n### {rel(f)}\n- !! {info['error']}")
            continue
        header = f"\n### {rel(f)}" + (f" — {info['doc']}" if info["doc"] else "")
        body = []
        for name, d, methods in info["classes"]:
            n_classes += 1
            body.append(f"- class **{name}**{' — ' + d if d else ''}" + (f" [{', '.join(methods[:8])}]" if methods else ""))
        for name, args, d in info["functions"]:
            n_funcs += 1
            body.append(f"- {name}({args}){' — ' + d if d else ''}")
        for imp in info["imports"]:
            edges.append((rel(f), imp))
        if body or info["doc"]:
            lines.append(header)
            lines += body

    lines.append("\n## Frontend & E2E (TypeScript)")
    for f in iter_files(TS_ROOTS, (".ts", ".tsx")):
        info = parse_ts(f)
        n_files += 1
        if not info["exports"] and not info["imports"]:
            continue
        lines.append(f"\n### {rel(f)}")
        for e in info["exports"][:12]:
            n_exports += 1
            lines.append(f"- exports {e}")
        for imp in info["imports"]:
            edges.append((rel(f), imp))

    lines.append("\n## Import graph (who depends on what)")
    for src, dst in edges:
        lines.append(f"- {src} → {dst}")

    lines.append("")
    summary = f"{n_files} files · {n_classes} classes · {n_funcs} functions · {n_exports} TS exports · {len(edges)} import edges"
    lines.append(f"_Totals: {summary}_")
    print(f"graphify: {summary} → {rel(OUT)}")
    return "\n".join(lines) + "\n"


def main() -> int:
    content = build()
    if "--check" in sys.argv:
        if not OUT.exists() or OUT.read_text(encoding="utf-8") != content:
            print("graphify: map is STALE — run `bash scripts/graphify.sh`", file=sys.stderr)
            return 1
        print("graphify: map is current")
        return 0
    OUT.parent.mkdir(parents=True, exist_ok=True)
    # encoding is explicit: Windows defaults to cp1252, which can't encode the arrows in the map
    OUT.write_text(content, encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main())
